### PR TITLE
feat: `texemail`: add support for more clipboard copiers

### PR DESCRIPTION
**Pull request by cviner**
Improves portability, allowing this to work on MacOS. Performed minor refactoring of platform-specific code.

### CODE REVIEW

**Comment by michaelmhoffman** [comment]
I've made some changes to this pull request on my local computer. Can you please set things up so that I can edit your pull request?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by cviner** [comment]
Looks like I already had enabled edits by maintainers. Can you not edit it? I'm not sure how else to enable that.

**Comment by michaelmhoffman** [comment]
I pushed the changes to your fork. Can you please verify it still works for you?

**Comment by cviner** [comment]
Just tested and it still works!

**Pull request merged**
